# Generated by Django 5.2.6 on 2025-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('poster_url', models.URLField()),
                ('trailer_url', models.URLField()),
                ('status', models.CharField(choices=[('RUNNING', 'Currently Running'), ('COMING_SOON', 'Coming Soon')], max_length=20)),
                ('genre', models.ManyToManyField(to='posts.genre')),
            ],
        ),
    ]
