# Generated by Django 5.2.6 on 2025-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('trailer_id', models.CharField(blank=True, max_length=20)),
                ('movie_poster_URL', models.URLField(blank=True)),
                ('genre', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('currently-running', 'Currently Running'), ('coming-soon', 'Coming Soon')], default='currently-running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
