# Generated by Django 5.2.6 on 2025-10-28 02:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_paymentcard_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('loyalty_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('promo_code', models.CharField(blank=True, max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='posts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay')], default='CARD', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('provider_ref', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='posts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField()),
                ('exp_year', models.PositiveSmallIntegerField()),
                ('cardholder_name', models.CharField(blank=True, max_length=100)),
                ('billing_zip', models.CharField(blank=True, max_length=20)),
                ('saved_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='posts.savedpaymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('movie_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='posts.movieroom')),
            ],
            options={
                'unique_together': {('movie_room', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('DOLBY', 'Dolby Cinema')], default='2D', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='posts.movie')),
                ('movie_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='posts.movieroom')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('ticket_type', models.CharField(choices=[('ADULT', 'Adult'), ('STUDENT', 'Student'), ('CHILD', 'Child'), ('SENIOR', 'Senior')], default='ADULT', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='posts.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='posts.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='posts.showtime')),
            ],
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['starts_at'], name='posts_showt_starts__2b732f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('movie_room', 'starts_at')},
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('showtime', 'seat'), name='unique_seat_per_showtime'),
        ),
    ]
