# Generated by Django 5.2.6 on 2025-12-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_promotion_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscribed_to_promotions',
            field=models.BooleanField(default=True),
        ),
    ]
